=== npalko/Torque-Extensions/torque-extensions.dtd
<!-- torque-extensions.dtd
     Torque Extensions XML database schema DTD 	
     http://github.com/npalko/Torque-Extensions -->

<!ELEMENT database (table+)>
<!ATTLIST database
  name CDATA #REQUIRED
  interfaceName CDATA #IMPLIED
>

<!ELEMENT table (column+, index*, foreign-key*)>
<!ATTLIST table
  name CDATA #REQUIRED
  interfaceName CDATA #IMPLIED
  description CDATA #IMPLIED
>

<!ELEMENT column EMPTY>
<!ATTLIST column
  name CDATA #REQUIRED
  interfaceName CDATA #IMPLIED
  type (TINYINT|SMALLINT|INT|BIGINT|DECIMAL|SINGLE|DOUBLE|TIME|DATE|TIMESTAMP
        |CHAR|VARCHAR|BIT|BINARY) #REQUIRED
  interfaceType (single|double|decimal|int16|int32|int64|string|date) #IMPLIED
  primaryKey (True|False)  #IMPLIED
  nullable (True|False)  #IMPLIED
  default CDATA #IMPLIED
  defaultIsNull (True|False) #IMPLIED
  autoIncrement (True|False) #IMPLIED
  length CDATA #IMPLIED
  precision CDATA #IMPLIED
  scale CDATA #IMPLIED
  description CDATA #IMPLIED
>

<!ELEMENT foreign-key EMPTY>
<!ATTLIST foreign-key
  name CDATA #IMPLIED
  referencedTable CDATA #REQUIRED
  referencedColumn CDATA #REQUIRED
  restrictedColumn CDATA #REQUIRED
  onUpdate (Cascade|SetNull|Restrict|None) #REQUIRED
  onDelete (Cascade|SetNull|Restrict|None) #REQUIRED
>

<!ELEMENT index (index-column+)>
<!ATTLIST index
  name CDATA #IMPLIED
  description CDATA #IMPLIED
  unique (True|False) #REQUIRED
  ascendingOrder (True|False) #IMPLIED
>

<!ELEMENT index-column EMPTY>
<!ATTLIST index-column
  name CDATA #REQUIRED
>

=== npalko/Torque-Extensions/Symbology.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE database SYSTEM "http://github.com/npalko/Torque-Extensions/raw/master/torque-extensions.dtd">
<database name="Symbology">
  <table name="Currency">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Last.Effective.Date" type="DATE" nullable="TRUE"/>
    <column name="ISO.Code" type="CHAR" description="ISO 4217 code" length="3"/>
    <column name="ISO.Number" type="INT" description="ISO 4217 number"/>
    <column name="Name" type="VARCHAR" length="100"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
  </table>
  <table name="Country">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Last.Effective.Date" type="DATE" nullable="TRUE"/>
    <column name="ISO.Code" type="CHAR" description="ISO 3166-1 alpha-3 " length="3"/>
    <column name="ISO.Number" type="INT" description="ISO 3166-1 numeric "/>
    <column name="Name" type="VARCHAR" length="100"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
  </table>
  <table name="Company">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Last.Effective.Date" type="DATE" description="in the event of a name change, this column is populated with the date the name was last effective" nullable="TRUE"/>
    <column name="Previous.Company.Id" type="INT" nullable="TRUE"/>
    <column name="Name" type="VARCHAR" description="Full name of the company" length="100"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
    <index name="fk_Company_Company1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Previous.Company.Id"/>
    </index>
    <foreign-key name="fk_Company_Company1" referencedTable="Company" referencedColumn="Id" restrictedColumn="Previous.Company.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
  </table>
  <table name="Security">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Underlying.Security.Id" type="INT" nullable="TRUE"/>
    <column name="Company.Id" type="INT"/>
    <column name="Instrument.Id" type="INT"/>
    <column name="Currency.Id" type="INT"/>
    <column name="Strike" type="DECIMAL" description="strike price for securities with optionality" precision="18" scale="6" nullable="TRUE"/>
    <column name="Expiration.Date" type="DATE" nullable="TRUE"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
    <index name="fk_Security_Security1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Underlying.Security.Id"/>
    </index>
    <index name="fk_Security_Company1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Company.Id"/>
    </index>
    <index name="fk_Security_Instrument1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Instrument.Id"/>
    </index>
    <index name="fk_Security_Currency1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Currency.Id"/>
    </index>
    <foreign-key name="fk_Security_Security1" referencedTable="Security" referencedColumn="Id" restrictedColumn="Underlying.Security.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
    <foreign-key name="fk_Security_Company1" referencedTable="Company" referencedColumn="Id" restrictedColumn="Company.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
    <foreign-key name="fk_Security_Instrument1" referencedTable="Instrument" referencedColumn="Id" restrictedColumn="Instrument.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
    <foreign-key name="fk_Security_Currency1" referencedTable="Currency" referencedColumn="Id" restrictedColumn="Currency.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
  </table>
  <table name="Instrument">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Parent.Instrument.Id" type="INT" nullable="TRUE"/>
    <column name="Name" type="VARCHAR" length="100"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
    <index name="instrument-1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
    <foreign-key name="instrument-1" referencedTable="Instrument" referencedColumn="Parent.Instrument.Id" restrictedColumn="Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
  </table>
  <table name="Industry.Classification.System">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Name" type="VARCHAR" length="100"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
  </table>
  <table name="Industry.Level">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Last.Effective.Date" type="DATE" nullable="TRUE"/>
    <column name="Industry.Classification.System.Id" type="INT"/>
    <column name="Code" type="VARCHAR" length="100"/>
    <column name="Name" type="VARCHAR" length="100"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
    <index name="fk_Industry.Level_Industry.Classification.System1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Industry.Classification.System.Id"/>
    </index>
    <foreign-key name="fk_Industry.Level_Industry.Classification.System1" referencedTable="Industry.Classification.System" referencedColumn="Id" restrictedColumn="Industry.Classification.System.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
  </table>
  <table name="Industry">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Last.Effective.Date" type="DATE" nullable="TRUE"/>
    <column name="Parent.Industry.Id" type="INT" nullable="TRUE"/>
    <column name="Industry.Classification.System.Id" type="INT"/>
    <column name="Industry.Level.Id" type="INT"/>
    <column name="Code" type="VARCHAR" length="100"/>
    <column name="Name" type="VARCHAR" length="100"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
    <index name="fk_Industry_Industry.Classification.System1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Industry.Classification.System.Id"/>
    </index>
    <index name="fk_Industry_Industry.Level1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Industry.Level.Id"/>
    </index>
    <index name="fk_Industry_Industry1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Parent.Industry.Id"/>
    </index>
    <foreign-key name="fk_Industry_Industry.Classification.System1" referencedTable="Industry.Classification.System" referencedColumn="Id" restrictedColumn="Industry.Classification.System.Id" onUpdate="NONE" onDelete="NONE"/>
    <foreign-key name="fk_Industry_Industry.Level1" referencedTable="Industry.Level" referencedColumn="Id" restrictedColumn="Industry.Level.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
    <foreign-key name="fk_Industry_Industry1" referencedTable="Industry" referencedColumn="Id" restrictedColumn="Parent.Industry.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
  </table>
  <table name="Counter.Party">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Exchange.Id" type="INT" nullable="TRUE"/>
    <column name="Synthetic.Exchange.Id" type="INT" nullable="TRUE"/>
    <column name="Broker.Id" type="INT" nullable="TRUE"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
    <index name="fk_Counter.Party_Broker1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Broker.Id"/>
    </index>
    <index name="fk_Counter.Party_Exchange1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Exchange.Id"/>
    </index>
    <index name="fk_Counter.Party_Synthetic.Exchange1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Synthetic.Exchange.Id"/>
    </index>
    <foreign-key name="fk_Counter.Party_Broker1" referencedTable="Broker" referencedColumn="Id" restrictedColumn="Broker.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
    <foreign-key name="fk_Counter.Party_Exchange1" referencedTable="Exchange" referencedColumn="Id" restrictedColumn="Exchange.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
    <foreign-key name="fk_Counter.Party_Synthetic.Exchange1" referencedTable="Synthetic.Exchange" referencedColumn="Id" restrictedColumn="Synthetic.Exchange.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
  </table>
  <table name="Exchange">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Last.Effective.Date" type="DATE" nullable="TRUE"/>
    <column name="Sequence" type="INT"/>
    <column name="Country.Id" type="INT"/>
    <column name="ISO.Code" type="CHAR" description="ISO 10383 Market Identifier Code (MIC)" length="4"/>
    <column name="Name" type="VARCHAR" length="100"/>
    <column name="Website" type="VARCHAR" length="100" nullable="TRUE"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
    <index name="fk_Exchange_Country1" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Country.Id"/>
    </index>
    <foreign-key name="fk_Exchange_Country1" referencedTable="Country" referencedColumn="Id" restrictedColumn="Country.Id" onUpdate="RESTRICT" onDelete="RESTRICT"/>
  </table>
  <table name="Synthetic.Exchange">
    <column name="Id" type="INT" primaryKey="TRUE" autoIncrement="TRUE"/>
    <column name="Name" type="VARCHAR" length="100"/>
    <index name="PRIMARY" unique="FALSE" ascendingOrder="TRUE">
      <index-column name="Id"/>
    </index>
  </table>
  <table name="Broker">
